// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: profiles.sql

package db

import (
	"context"
)

const selectProfiles = `-- name: SelectProfiles :many
SELECT did, lexicon, handle, created, ingested, updated, rev, sig, version FROM atgraph.profiles
`

func (q *Queries) SelectProfiles(ctx context.Context) ([]AtgraphProfile, error) {
	rows, err := q.db.QueryContext(ctx, selectProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AtgraphProfile
	for rows.Next() {
		var i AtgraphProfile
		if err := rows.Scan(
			&i.Did,
			&i.Lexicon,
			&i.Handle,
			&i.Created,
			&i.Ingested,
			&i.Updated,
			&i.Rev,
			&i.Sig,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
