services:
  neo4j:
    image: neo4j:5.26.2-community-bullseye 
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: none
      NEO4J_initial_dbms_default__database: bluesky
      NEO4J_server_bolt_telemetry_enabled: true
      NEO4J_dbms_usage__report_enabled: false
      # query.log gated in enterprise edition
      NEO4J_db_logs_query_enabled: INFO
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - neo4j_net

volumes:
  neo4j_data:
  neo4j_logs:

networks:
  neo4j_net:
    driver: bridge
