---
global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:9464']

  - job_name: 'neo4j'
    static_configs:
      - targets: ['neo4j:2004']
