package bsky

const (
	ENV_BSKY_PDS_URL           = "BSKY_PDS_URL"
	ENV_BSKY_IDENTIFIER        = "BSKY_IDENTIFIER"
	ENV_BSKY_PASSWORD          = "BSKY_PASSWORD"
	ENV_BSKY_PAGE_SIZE         = "BSKY_PAGE_SIZE"
	ENV_BSKY_REPO_WORKER_COUNT = "BSKY_REPO_WORKER_COUNT"

	// defaults
	BSKY_SOCIAL_URL      = "https://bsky.social"
	DEFAULT_PAGE_SIZE    = 1000
	DEFAULT_WORKER_COUNT = 3
)
